### ISSUE TITLE
have to put coordinates as decimal

### ISSUE THREAD

**Issue by jidanni** [smeijer/leaflet-geosearch#147]
In 
https://framagit.org/PanierAvide/Pic4Carto/issues/34#note_145601
I was told to report weird behavior here.

**Comment by PanierAvide** [comment]
To be more precise, when entering `24,121` lat/lng coordinates, you don't end up near these coordinates but `60.76244, 30.14387` instead. Happens with version 1.0.0 (from npm).

**Comment by smeijer** [comment]
I'm not sure if there is anything we can do. Searching for coordinates is only working because your provider is handling them. For example the openstreetmap provider just gives different results for [`52,6`][1] vs [`52.0,6.0`][2].

What we could do, is add a option to handle numeric input as being lat/lon. For backwards compatibility, this should be optional / configurable.

See this urls:
[1]: https://nominatim.openstreetmap.org/search?format=json&q=52%2C6
[2]: https://nominatim.openstreetmap.org/search?format=json&q=52.0%2C6.0
