### ISSUE TITLE
LOOKING FOR MAINTAINERS

### ISSUE THREAD

**Issue by smeijer** [smeijer/leaflet-geosearch#172]
## THANK YOU FOR YOUR CONTRIBUTIONS

Let's be honest; this project would already be dead if you all hadn't created `issues` and `pull requests`. You guys/girls are awesome, and helped this packaged to grow to the next level. So again; **Thanks for your contributions!**

## LOOKING FOR MAINTAINERS

Now back on topic; because that's where issues are for. I'm looking for maintainers, as I have a huge lack of time.

The [network chart](https://github.com/smeijer/leaflet-geosearch/network) shows that there is still a lot of activity arround this project, we just need to speed up the issue / PR processes to merge the fixed bugs / added functionality. And for that; I need time or your help.

So, are you interested? Please let me know. Here in the comments or hit me on [gitter](https://gitter.im/smeijer/leaflet-geosearch).

**Comment by jlengrand** [comment]
Hey there, 

I haven't used leaflet-geosearch in a while, so I won't offer myself to become a maintainer. 
However I want to salute your initiative and openness. Lots of projects just go to die because the creator stops showing up, and asking for help requires honesty.

Kudos to you, and long live leaflet-geosearch!

**Comment by skipjack** [comment]
@smeijer I may be able to help. I've worked with `leaflet` for years and have started digging into `react-leaflet` as well more recently, so I'm pretty familiar with the space. The next couple months aren't great for me but if you haven't found anyone by the end of the year, ping me and I'll see if I can help.

**Comment by smeijer** [comment]
Thanks for the kind words here. Still looking for help. So a bump from my side 😇

**Comment by jlengrand** [comment]
Hey there. 

I'm not offering my help because I am not very involved with GIS related projects lately, so my comment will be moderately useful. But I wanted to send virtual love kudos! It's a lot of work to maintain a successful project, and a lot of people are using this plug-in. 

Best of luck in finding a reliable person to help!

**Comment by mossplix** [comment]
Hi there,
I am offering to help maintain this. I love leaflet and I have used it many of my projects. let me know if you are still looking for help

**Comment by mossplix** [comment]
@smeijer Please let me know If you are still looking for a maintainer

**Comment by smeijer** [comment]
@mossplix, definitely. Maybe you can hit me on Gitter, so we can talk about it and make a plan?

[![Join the chat at https://gitter.im/smeijer/leaflet-geosearch](https://badges.gitter.im/smeijer/leaflet-geosearch.svg)](https://gitter.im/smeijer/leaflet-geosearch?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by mfreeman451** [comment]
whats going on with this..

**Comment by smeijer** [comment]
I'm still lacking time. At moments I think I can spend a day to go trough some issues, but when the day comes, paid jobs are taking priority.

I'll try to free some schedule. This project definitely deserves more love than it's currently receiving.

**Comment by dimabory** [comment]
@smeijer I can join and help you if you need anything. Just let me know ✌

**Comment by vstyle** [comment]
Hi there, sorry for offtopic question, I guess the leaflet-geosearch doesn't work with 1.5.1 leaflet version, isn't it?

**Comment by yzinets** [comment]
Hello, @smeijer!
I'm interested in contributing to this repo (provider for Algolia Places) due to using that in another project.
Please, can you provide detailed steps for contributing to this project? I think it would be much easier for others to maintain/contribute.
F.e. I was a bit confused when I got errors while first `yarn install` (errors related to not passed tests). In my opinion, installing dependencies is not related to tests at all 😅
Thank you very much for your contribution to Open Source!

**Comment by smeijer** [comment]
I've just released v3.0.0, and am closing this issue. I'm still open for contributions, and they would be most welcome. But I'm reprioritizing open-source projects, and am about to spend a bit more time on them. 

To get started, I've rewritten the project to typescript, so that `leaflet-geosearch` comes with typescript out of the box.

I've also merged a number of pull-requests, thanks to which we now have an [AlgoliaProvider](https://smeijer.github.io/leaflet-geosearch/providers/algolia) (thanks @yzinets!) and a [HereProvider](https://smeijer.github.io/leaflet-geosearch/providers/here) (thanks to @IvelinYR).

Also, numerous long-standing issues have been fixed. At this moment, there is only one edge case remaining, that relates to the OpenStreetMap provider (#180).

All other currently open tickets are either feature requests, or documentation issues/questions. On which I will work in the upcoming weeks.

Talking about the documentation, that has been improved as well. See here: https://smeijer.github.io/leaflet-geosearch

Again, thank you all for your support and patience. I'll do my absolute best to bring more life into this project.
