### ISSUE TITLE
[bower] dist files

### ISSUE THREAD

**Issue by mjvanderveen** [smeijer/leaflet-geosearch#95]
Hi Stephan,

I am upgrading from version 1. However, your new version 2 doesn't seem to have the dist in the git repo when I install it through bower install. The npm install does have the dist files.

**Comment by smeijer** [comment]
Npm works with a `prepublish` script. Could you point me in the right direction for bower? I have no experience with bower.

**Comment by ville6000** [comment]
Bower is recommending using Yarn or webpack so this issue could be closed.

**Comment by smeijer** [comment]
I agree that it can be closed, but than we should first remove `bower.json` from the source. And perhaps unpublish some package? I don't know how that works yet.

**Comment by smeijer** [comment]
I was a little hesitant to close this one, due to a conversation I had on gitter with @drspangle. I decided to not postpone this any longer, and resolved the issue.

As @ville6000 writes, Bower recommends using Yarn over it's own program.  To quote:

> ...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!

So it's time for us to speak the truth; this library cannot support bower any longer.
